Ingest entities and relationships
JupiterOne/graph-checkmarx pull request #2
Opened 2020-11-05 00:06 UTC by eXtremeX

This PR includes [Checkmarx](https://www.checkmarx.com/) integration.

Some links that could be useful to anyone trying to familiarize with Checkmarx a bit more:
1) [Checkmarx Knowledge Center](https://checkmarx.atlassian.net/wiki/spaces/KC/overview)  
2) [Checkmarx Swagger API Reference](https://cxprivatecloud.checkmarx.net/cxrestapi/help/swagger/ui/index)  

Some questions/interesting things from our end:
1) The `projectSteps` function currently isn't assigning webLink. We could point to a 'static' https://{workspace}.checkmarx.net/CxWebClient/Projects.aspx which shows all the projects for the given workspace (every project would lead to the same page then), but there doesn't seem to be a way to directly link to some particular project (either manually using the dashboard or with data that we receive back for each and every project).
2) Similar situation with `teamSteps` function. When you use dashboard, as soon as you log in you're logged in to that particular team it seems and there's no way (that we know of) of seeing, say a list of teams or adding a new one (might be part of registration?). API gives us a field they call fullName that contains the value "/CxServer/SP/Partners/JupiterOne", which kind of seems like a link pointing to a particular team (the team name here is indeed JupiterOne), but after trying few ways of using this fullName we couldn't get to any dashboard page.
3) [Finding class](https://github.com/JupiterOne/data-model/blob/master/src/schemas/Finding.json) requires the following fields: "category", "severity", "numericSeverity", "open".
In our `scanFindingsSteps` function (which handles Finding entities), we've set the **category** to 'software' (is this correct?).
For the **severity**, luckily Checkmarx API does return a field called `Result Severity` and with our limited sample size we've seen that its values include "Low" and "Medium". We're mapping that directly to the **severity** field. (should be correct we think).
For the **numericSeverity** we added a mapping function that maps `Result Severity` into a number (0-4), however, we haven't been able to learn what are all the possible values that it may return from their [API docs](https://cxprivatecloud.checkmarx.net/cxrestapi/help/swagger/ui/index#!/GENERAL/Reports_GetByid) so we just guessed that it might be "Low", "Medium", "High" and we return a number based on that. We may want to change the logic here. (The mapping function is located in the same scanFindingsSteps file).
For the **open**, we currently set it to always be true which might be a mistake too - it just seems a bit hard to tell that from the data we get for each and every finding.
4) The "Provider account setup" bit from the docs/development.md is missing - the reason is that we got credentials handed to us by you and it seems that their site doesn't have the usual "sign up" page plus we haven't gone through that registration/setup process yet. Should we do something here?

Kindly let us know if something needs to be changed. @aiwilliams @ndowmon

### Mappings
![mapping](https://user-images.githubusercontent.com/8009142/98181165-f4a85400-1f02-11eb-81ad-5390da5e906d.png)

### State of the graph
![checkmarx_graph](https://user-images.githubusercontent.com/8009142/98180809-308ee980-1f02-11eb-887d-989ecfb3d401.png)

2020-11-10 16:22 UTC, aiwilliams requested changes
Thanks for this work @eXtremeX ! The integration looks great. There are some changes that will need to be in place to limit the data ingested, based on my understanding of Checkmarx at this time, as well as a few other small things/questions.

2020-11-10 16:22 UTC, aiwilliams commented on src/client.ts
> +      this.withBaseUri(`sast/scans?projectId=${projectId}`),
Also, looking at the UI, I think we should only fetch the `last=1` scan for each project. Here is an example of 4 scans against a single project:

![Screen Shot 2020-11-10 at 11 04 22 AM](https://user-images.githubusercontent.com/2571/98698924-93d6ac80-2344-11eb-9b4a-c1f714c8f7de.png)

This number of vulnerabilities over time as scans were executed:

![Screen Shot 2020-11-10 at 11 05 18 AM](https://user-images.githubusercontent.com/2571/98699024-ad77f400-2344-11eb-8835-0649aeb673ef.png)

Since we aim to reflect the current set of open findings, we really just need the last Regular scan of a host I suppose, thought again, I'm not a Checkmarx expert. We can start with these more limited sets of data and once we have customers using it, we can learn more about what we need.

2020-11-10 16:22 UTC, aiwilliams commented on src/constants.ts
> +> = {
This all looks great, thanks for picking up the newer patterns!

2020-11-10 16:22 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +}
Nice use of the only unique thing in the scan findings! How do you feel about dropping everything up to and including the query `?` in `https://cxprivatecloud.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1000990&projectid=328&pathid=1`, so that the key is `checkmarx_finding:scanid=1000990&projectid=328&pathid=1`?

2020-11-10 16:22 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +      if (scanEntity.status !== 'Failed') {
I think we can drop this check when we only ingest `Finished` scans.

2020-11-10 16:22 UTC, aiwilliams commented on src/steps/index.test.ts
> +    ).toMatchGraphObjectSchema({
Thanks for providing these schema checks!

2020-11-10 16:22 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +            });
Another property we'll need on the finding entity: `targets: ['<project name>']`. This will allow the system mapper to relate the finding to any `CodeRepo` etc. that has the same name.

2020-11-10 16:46 UTC, aiwilliams commented
> The projectSteps function currently isn't assigning webLink. We could point to a 'static' https://{workspace}.checkmarx.net/CxWebClient/Projects.aspx which shows all the projects for the given workspace (every project would lead to the same page then), but there doesn't seem to be a way to directly link to some particular project (either manually using the dashboard or with data that we receive back for each and every project).

How about linking to the project's scans, such as https://cxprivatecloud.checkmarx.net/CxWebClient/projectscans.aspx?id=396 ?

> Similar situation with teamSteps function. When you use dashboard, as soon as you log in you're logged in to that particular team it seems and there's no way (that we know of) of seeing, say a list of teams or adding a new one (might be part of registration?). API gives us a field they call fullName that contains the value "/CxServer/SP/Partners/JupiterOne", which kind of seems like a link pointing to a particular team (the team name here is indeed JupiterOne), but after trying few ways of using this fullName we couldn't get to any dashboard page.

I'm thinking that since we're on an NFR license, we're restricted to a team within a deployment of the platform for trials/NFR/Partners. I think we can leave the Team webLink undefined.

> Finding class requires the following fields: "category", "severity", "numericSeverity", "open".
> In our scanFindingsSteps function (which handles Finding entities), we've set the category to 'software' (is this correct?).

We're using [`system-scan`](https://github.com/JupiterOne/graph-qualys/blob/10ccf0624bf8a00e72dad98e0d5e22a7ac74cf21/src/steps/vmdr/converters.ts#L196) for host scans, and [`app-scan`](https://github.com/JupiterOne/graph-qualys/blob/10ccf0624bf8a00e72dad98e0d5e22a7ac74cf21/src/steps/was/converters.ts#L47) for web application scans. Checkmarx SAST scans I think could be `sast-scan`.

> For the severity, luckily Checkmarx API does return a field called Result Severity and with our limited sample size we've seen that its values include "Low" and "Medium". We're mapping that directly to the severity field. (should be correct we think).
> For the numericSeverity we added a mapping function that maps Result Severity into a number (0-4), however, we haven't been able to learn what are all the possible values that it may return from their API docs so we just guessed that it might be "Low", "Medium", "High" and we return a number based on that. We may want to change the logic here. (The mapping function is located in the same scanFindingsSteps file).

This makes good sense! Please take a look at the Qualys integration's [handling of severity/numericSeverity normalization](https://github.com/JupiterOne/graph-qualys/blob/10ccf0624bf8a00e72dad98e0d5e22a7ac74cf21/src/steps/utils.ts#L54). We're aiming to have the numericSeverity run between 1 - 10.

> For the open, we currently set it to always be true which might be a mistake too - it just seems a bit hard to tell that from the data we get for each and every finding.

That makes sense! I think that we can hard code as open for now, since any finding in the last scan is open as far as we know.

> The "Provider account setup" bit from the docs/development.md is missing - the reason is that we got credentials handed to us by you and it seems that their site doesn't have the usual "sign up" page plus we haven't gone through that registration/setup process yet. Should we do something here?

I think just change to something like "Please contact whomever currently has access to your organization's Checkmarx account to get credentials." :)

2020-11-10 19:34 UTC, mknoedel commented on src/client.ts
> +    const maxLoops = 5;
It might be nice to throw an error or otherwise record when reports aren't completed in time.

2020-11-10 20:07 UTC, mknoedel commented on src/steps/projects.ts
> +    if (teamEntity) {
Is it only important to create a projectEntity if the related teamEntity exists or can there be free-floating projects?

2020-11-10 20:10 UTC, mknoedel commented on src/steps/scan-findings.ts
> +}
Should we trust the order of the query parameters to be consistent? If that is a worry then they could be ordered first.

2020-11-11 13:22 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +}
That's a great question. Perhaps we should even make the function read each value, verifying they all three exist, and then combining them in a stable order.

2020-11-11 13:25 UTC, aiwilliams commented on src/steps/projects.ts
> +    if (teamEntity) {
I'm not sure whether projects _can_ exist apart from teams, but I think we do want the projects ingested even when there are no associated teams.

2020-11-11 13:42 UTC, aiwilliams requested changes

2020-11-11 13:42 UTC, aiwilliams commented on src/client.ts
> +    const maxLoops = 5;
Glad you raised this @mknoedel. Integrations have to walk a line of resiliency in the face of errors and avoiding incomplete data. It's a bit of a judgement call in each case.

In this case, the integration is ingesting all open security findings every time it runs, so we can get away with skipping a report for intermittent HTTP errors. As you suggest, we can just record the failure. I'll add additional comments to the code below.

2020-11-11 13:42 UTC, aiwilliams commented on src/client.ts
> +            console.warn('unable to parse scan report csv', err);
We need all logging to go through the `IntegrationLogger`. To make this possible, there are two patterns we've used:

1. Make the `APIClient` constructor receive the `logger: IntegrationLogger` and store as an instance variable
2. Make the `iterate*` functions receive an error callback [like we do in Qualys](https://github.com/JupiterOne/graph-qualys/blob/10ccf0624bf8a00e72dad98e0d5e22a7ac74cf21/src/provider/client/index.ts#L336)

The callback is the better pattern because it allows the caller to decide what to do for any error. The constructor approach is much simpler, and I think you could take that approach here. Then this would become:

```
logger.warn({ err, scanId, reportId }, 'Failed to parse scan report CSV');
```

2020-11-11 13:42 UTC, aiwilliams commented on src/client.ts
> +
I think here would log something like:
```
logger.warn({ err, scanId }, 'Failed to obtain scan report within %i seconds', totalWaitSeconds);
```

2020-11-11 19:44 UTC, eXtremeX commented on src/client.ts
> +  private static accessToken: string;
Good question! Our logic for figuring out whether we need to fetch accessToken is based on the accessToken variable's data (if it's undefined, we need to fetch accessToken and populate it). Reminder: this time around we need to actively fetch accessToken every time integration is running, we don't have it as an environment variable, etc.

At first, it was instance variable and that worked, but because each step function would create its own APIClient instance, that meant we'd fire many more calls to Checkmarx to fetch the same accessToken again and again and this switch to static class variable made it so only one call for fetching accessToken was required per run - felt like an improvement at the time and also felt a bit safer to keep the API calls down if possible.

Do you see something wrong with this approach and/or have some other ideas @aiwilliams ?

2020-11-11 19:45 UTC, eXtremeX commented on src/client.ts
> +        client_secret: '014DF517-39D1-4453-B7B3-9930C563627C',
It's not, it's something Checkmarx docs told us to use:

> client_secret: Value must be set as '014DF517-39D1-4453-B7B3-9930C563627C'
from https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1187774721/Using+the+CxSAST+REST+API+v8.6.0+and+up

2020-11-11 19:58 UTC, eXtremeX commented on src/client.ts
> +    const response = await this.request(this.withBaseUri('projects'));
I don't think I have actually, so good question :slightly_smiling_face: Based on what we've seen, there doesn't seem to be pagination. :man_shrugging:

For example, for the **projects** endpoint mentioned in this question, these two pages are of main interest:
1) https://checkmarx.atlassian.net/wiki/spaces/KC/pages/360022226/Get+All+Project+Details+-+GET+projects
2) https://cxprivatecloud.checkmarx.net/cxrestapi/help/swagger/ui/index#!/GENERAL/ProjectsManagement_GetByprojectNameteamId

Neither mentions pagination when they go over the accepted params... Also, [searching their knowledge center for keyword "pagination"](https://checkmarx.atlassian.net/wiki/search?text=pagination&search_id=cad2da00-6f21-4d11-8669-ba78253e6387) doesn't seem to return anything for API.

2020-11-11 19:58 UTC, eXtremeX commented on src/client.ts
> +    const response = await this.request(this.withBaseUri('auth/teams'));
Similar answer as [above](https://github.com/JupiterOne/graph-checkmarx/pull/2#discussion_r520608386) here

2020-11-11 19:59 UTC, eXtremeX commented on src/client.ts
> +   */
Will fix that, thanks for pointing out! :+1:

2020-11-11 20:06 UTC, eXtremeX commented on src/steps/__recordings__/checkmarx_recordings_3793889096/recording.har
> +            "text": "username=adam.williams%40jupiterone.com&password=tfpc%2FCaY%5BXobuF9&grant_type=password&scope=sast_rest_api&client_id=resource_owner_client&client_secret=014DF517-39D1-4453-B7B3
Ouch, sorry about that! :sweat: Haven't had similar things happen with previous integrations so we overlooked this. 
Thanks for the link, we'll make the necessary modification.

Shouldn't be worried about `client_secret`, it's not much of a secret it seems (explained in the [above comment](https://github.com/JupiterOne/graph-checkmarx/pull/2#discussion_r521597387)) and can't be edited.

2020-11-11 20:15 UTC, eXtremeX commented on src/steps/__snapshots__/index.test.ts.snap
> +            "links": Array [
Sounds good, will do!

2020-11-11 20:19 UTC, eXtremeX commented on src/client.ts
> +      this.withBaseUri(`sast/scans?projectId=${projectId}`),
Makes sense now that you said it! :+1:  We'll go with this more limited sets of data idea for now.

2020-11-11 20:23 UTC, eXtremeX commented on src/steps/scan-findings.ts
> +}
Yep, we didn't have lots to choose from that was unique :slightly_smiling_face: 

Great suggestions from both sides!

Another question - if we make that function that reads it, verifies it, and then combines them in a stable order to be used as a key should we care/handle (and if so, how) the case where some of the ['scanid', 'projectid', 'pathid'] values are missing?

Do we just use the same ordering but we omit the missing value in those edge-cases?

2020-11-11 20:32 UTC, eXtremeX commented on src/steps/projects.ts
> +    if (teamEntity) {
Same here - I'm not sure if they can (everything seems to be under the team), but let's make this modification just in case. We'll ingest the project as a node independently of team existence, but if the teamEntity also exists (we believe that it should), we'll build the relationship then.

2020-11-11 20:50 UTC, eXtremeX commented on src/client.ts
> +    const { reportId }: CheckmarxGeneratedReport = await response.json();
Sadly we haven't. I also checked it again right now but wasn't able to find anything on rate-limiting. I'm not saying they don't document it for sure, but at least not in some obvious places. Maybe you could ask your contact person at Checkmarx?

Other than that, concurrently triggering multiple report processes seems like a good idea.

2020-11-12 01:52 UTC, aiwilliams commented on src/client.ts
> +  private static accessToken: string;
Ah, that sounds like a good reason to try to keep the same token. I think we have similar behavior in some other integrations, since the client is recreated in each step. I'd like to see us work toward a design, in all integrations, where the authentication mechanism is a lazy resolved/refreshable mechanism similar to how the `aws-sdk` does it, and that thing moves across steps in the execution context for reuse.

I think this is fine for now! Probably worthwhile to add a comment about why it is a static variable so that should someone spend time trying to remove it, they realize they should think about maintaining the feature of not requesting a new token in each step.

2020-11-12 01:53 UTC, aiwilliams commented on src/client.ts
> +        client_secret: '014DF517-39D1-4453-B7B3-9930C563627C',
Would you mind placing that link as a comment for that property? Thanks!

2020-11-12 02:01 UTC, aiwilliams commented on src/client.ts
> +    const { reportId }: CheckmarxGeneratedReport = await response.json();
Okay, thanks for checking! I'm sure you're correct. Concurrency is probably as easy as a `p-queue` in the step with calls to `fetchScanReport()` for each scan. Then we can tune the `concurrency` setting.

2020-11-12 02:06 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +}
I suspect that if any one of the three values is missing, we'll end up with duplicate keys. 🤔  For now, how about let's make the function throw an `IntegrationError` that explains we didn't expect to see a finding with missing values, and say which were missing. We may never see that be a problem.

2020-11-13 15:31 UTC, eXtremeX commented on src/client.ts
> +    const { reportId }: CheckmarxGeneratedReport = await response.json();
Sounds good, p-queue has been added! :+1:

2020-11-13 15:32 UTC, eXtremeX commented on src/steps/index.test.ts
> +    ).toMatchGraphObjectSchema({
No problem! :slightly_smiling_face:

2020-11-13 15:34 UTC, eXtremeX commented on src/client.ts
> +            console.warn('unable to parse scan report csv', err);
Thanks for the explanation, I've added that callback approach - let me know if something is off!

2020-11-24 21:00 UTC, aiwilliams approved these changes
Thanks for making those changes @eXtremeX 👍  I think we're good to go for a beta release.

2020-11-24 21:00 UTC, merged

2020-11-24 21:04 UTC, aiwilliams commented on src/steps/scan-findings.ts
> +}
D'oh! I missed this in the PR view... would you make the change in a new PR to address this, at https://github.com/JupiterOne/graph-checkmarx/blob/934e9d81aaeb721667199ece17a8b9accb1506f5/src/steps/scan-findings.ts#L18, @eXtremeX ?

2020-11-25 12:18 UTC, eXtremeX commented on src/steps/projects.ts
> +    await Promise.all(jobs);
Sure @aiwilliams! We always want to ingest the project entity node and in case there's a team parent node (which we believe should always be the case) we also want to create a relationship between the project and the team.

The `jobs` approach allows us to do both of those operations in parallel in scenarios where there is a team parent node present and we're ingesting a new project node. Had we not used the `jobs` approach, the first async process (jobState.addEntity) would first need to be completed before the async relationship process can be started.

Another alternative (to not use `jobs` approach) can be this one perhaps:
   ```
const teamEntity = await jobState.findEntity(getTeamKey(project.teamId));

    if (teamEntity) {
      await Promise.all([
        jobState.addEntity(projectEntity),
        jobState.addRelationship(
          createDirectRelationship({
            _class: RelationshipClass.HAS,
            from: teamEntity,
            to: projectEntity,
          }),
        ),
      ]);
    } else {
      await jobState.addEntity(projectEntity);
    }
```

It's slightly less DRY however since the line `jobState.addEntity(projectEntity);` is repeated twice, but I guess it comes down to a preference :slightly_smiling_face: 

Also with the `jobs` approach, if we move the line `const jobs: Promise<any>[] = [];` just outside of `await apiClient.iterateProjects(async (project) => {` and we `await Promise.all(jobs);` at the bottom of the function, we could "schedule" all of those jobs for all the projects and then just Promise.all them exactly once (though I haven't tried this, just got an idea right now looking at the code - might not be a good idea since we usually are looking to process entities as they come from those iterate functions).

Let me know if this explains it!